- name: Deploy to tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy
      copy:
        src: "/var/snap/jenkins/5022/workspace/Ansible1/target/Ansible1.war"
        dest: "/opt/tomcat/webapps/Ansible1.war"
    - name: Restart
      shell: |
        /opt/tomcat/bin/shutdown.sh
        /opt/tomcat/bin/startup.sh
      
     
  
